#!/usr/bin/env python3
"""Package generated Markdown sermon/talk files into a ZIP."""

from __future__ import annotations

import argparse
import json
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a ZIP containing generated .md files and manifest.json."
    )
    parser.add_argument(
        "--source",
        required=True,
        help="Directory containing generated Markdown files.",
    )
    parser.add_argument(
        "--zip",
        required=True,
        dest="zip_path",
        help="Destination ZIP path.",
    )
    return parser.parse_args()


def collect_markdown(source: Path) -> list[Path]:
    return sorted(
        path
        for path in source.iterdir()
        if path.is_file() and path.suffix.lower() == ".md" and not path.name.startswith(".")
    )


def ensure_manifest(source: Path, markdown_files: list[Path]) -> Path:
    manifest = source / "manifest.json"
    if manifest.exists():
        return manifest

    payload = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "markdown_count": len(markdown_files),
        "files": [path.name for path in markdown_files],
        "note": "Auto-generated by scripts/package_markdown_batch.py because no manifest.json existed.",
    }
    manifest.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return manifest


def main() -> int:
    args = parse_args()
    source = Path(args.source).expanduser().resolve()
    zip_path = Path(args.zip_path).expanduser().resolve()

    if not source.exists() or not source.is_dir():
        print(f"ERROR: source directory not found: {source}", file=sys.stderr)
        return 2

    markdown_files = collect_markdown(source)
    if not markdown_files:
        print(f"ERROR: no .md files found in: {source}", file=sys.stderr)
        return 3

    manifest = ensure_manifest(source, markdown_files)
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in markdown_files:
            archive.write(path, arcname=path.name)
        archive.write(manifest, arcname="manifest.json")

    print(
        json.dumps(
            {
                "zip": str(zip_path),
                "markdown_count": len(markdown_files),
                "markdown_files": [path.name for path in markdown_files],
                "manifest": str(manifest),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
